### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by jrnold** [virgesmith/UKCensusAPI#14]
When submitting to JOSS the release version should be [tagged in GitHub](https://help.github.com/articles/creating-releases/) and match the version number in setup.py and also DESCRIPTION.

This is part of the JOSS review process: openjournals/joss-reviews#408.

**Comment by virgesmith** [comment]
Since tags can't be modified I shall leave this until last

**Comment by virgesmith** [comment]
Created 1.0.0 release
