### ISSUE TITLE
Declaring API key

### ISSUE THREAD

**Issue by Brissenden21** [virgesmith/UKCensusAPI#42]
Hi Andrew,

I hope you're doing well.

I'm relatively new at programming, and I'm trying to run the query from the Mac terminal. How am I supposed to access the cache and save my Unique ID to it?
I tried to run ukcensus-query "folder where I want the snippets to be saved" [MyUniqueID] but it didn't work. Running: ukcensus-query "folder where I want the snippets to be saved" --no-api-key works instead.

Finally, I have this problem when trying to download multiple geographies:
"Select Resolution: TYPE231,TYPE258,TYPE298
TYPE231,TYPE258,TYPE298 is not valid"

Thanks a lot for your time, and help,
Tito

**Comment by virgesmith** [comment]
Tito,
That scipt doesnt support passing the key as a command-line argument (although it's not a bad idea - feel free to request it). I'd explicitly create a cache dir then use it like so:
```
$ mkdir ukcensus_cache
$ ukcensus-query ./ukcensus_cache --no-api-key
...
```
When that works, you could do
```
$ echo [insert-your-api-key-here] > ./ukcensus_cache/NOMIS_API_KEY
$ ukcensus-query ./ukcensus_cache
```
On the geographies, I'm afraid only one geography at a time is supported. Again, I don't see why it couldn't be, so feel free to request this too.

**Comment by Brissenden21** [comment]
Hi Andrew,

Thanks a lot for your reply. It took me a while to make this work, but it finally does – thanks a lot really.
I’ll raise those requests.

Best
Tito
