### ISSUE TITLE
Scotland API not working

### ISSUE THREAD

**Issue by glederrey** [virgesmith/UKCensusAPI#50]
Dear authors, 

The API to get data from Scotland isn't working anymore. I get the following "error":
```
Unable to contact https://www.scotlandscensus.gov.uk/ods-web/download/getDownloadFile.html, operating in offline mode - pre-cached data only
```

However, since I never downloaded the data, I don't have cached data. Do you plan on fixing it at some point?

Thanks

**Comment by ld-archer** [comment]
Hi Gael,

We see this problem fairly regularly now it seems, its usually due to Scotland data changing their URLs or restructuring their database. I'll take a look at it in the next few days and will try to get it fixed this week.

Best,
Luke

**Comment by glederrey** [comment]
Hi Luke, 

Thank you very much! 

I'll wait for an update then. =)

Best,
Gael

**Comment by virgesmith** [comment]
@glederrey I've justed pushed a new release - 1.1.6 - that includes Tom's PR so should fix your issue. Please reopen if you still have problems. Thanks @tomalrussell  @ld-archer!

**Comment by glederrey** [comment]
Thanks a lot! I will try it during the week.
