### ISSUE TITLE
    query_params["uid"] = self.key TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by southplainfield** [virgesmith/UKCensusAPI#54]
Hi - apologies if i am missing something obvious but I cannot get the sample python snippet to run without adding 

query_params = {}

before line 203 in Nomisweb.py

query_params["uid"] = self.key

The error does make sense because checking type just before line 203 gives <class 'str'>

My API key is saved as an env variable. 

Thanks, David

![Screenshot (1)](https://user-images.githubusercontent.com/78021435/181034967-ea2cfcd7-1653-4baa-8282-775e185a0cb2.png)

**Comment by virgesmith** [comment]
Hi thanks for reporting. `table_internal` is no longer an argument to `get_data` but the docs weren't updated.

```py
KS401EW = api.get_data(table, query_params)
```

should fix it. I'll update the README.
